// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: blog.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/asim/go-micro/v3/api"
	client "github.com/asim/go-micro/v3/client"
	server "github.com/asim/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for BlogService service

func NewBlogServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for BlogService service

type BlogService interface {
	Detail(ctx context.Context, in *BlogRequest, opts ...client.CallOption) (*BlogResponse, error)
}

type blogService struct {
	c    client.Client
	name string
}

func NewBlogService(name string, c client.Client) BlogService {
	return &blogService{
		c:    c,
		name: name,
	}
}

func (c *blogService) Detail(ctx context.Context, in *BlogRequest, opts ...client.CallOption) (*BlogResponse, error) {
	req := c.c.NewRequest(c.name, "BlogService.Detail", in)
	out := new(BlogResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BlogService service

type BlogServiceHandler interface {
	Detail(context.Context, *BlogRequest, *BlogResponse) error
}

func RegisterBlogServiceHandler(s server.Server, hdlr BlogServiceHandler, opts ...server.HandlerOption) error {
	type blogService interface {
		Detail(ctx context.Context, in *BlogRequest, out *BlogResponse) error
	}
	type BlogService struct {
		blogService
	}
	h := &blogServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&BlogService{h}, opts...))
}

type blogServiceHandler struct {
	BlogServiceHandler
}

func (h *blogServiceHandler) Detail(ctx context.Context, in *BlogRequest, out *BlogResponse) error {
	return h.BlogServiceHandler.Detail(ctx, in, out)
}
